# Generated by Django 6.0.2 on 2026-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
