# Generated by Django 6.0.2 on 2026-02-20 17:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="experience_years",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="experience",
            field=models.DateField(
                blank=True,
                help_text="Date when you started your professional experience",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="resume",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload your resume (PDF, DOC, DOCX)",
                max_length=255,
                null=True,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Profile avatar image (JPG, PNG)",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
