# Generated by Django 6.0.2 on 2026-02-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0002_add_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="company_website",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="experience_years",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="resume",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skills",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
