# Generated by Django 6.0.2 on 2026-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentications", "0003_remove_userprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
