# Generated by Django 6.0.2 on 2026-02-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="salary_max",
            new_name="salary",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_min",
        ),
        migrations.AddField(
            model_name="job",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                default="company_logos/default.jpg",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
