# Generated by Django 6.0.2 on 2026-02-19 06:27

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    apps.core.validators.validate_file_size,
                ],
            ),
        ),
    ]
