# Generated by Django 6.0.2 on 2026-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_promoted",
            field=models.BooleanField(
                default=False, help_text="Whether job post is currently promoted"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="promoted_until",
            field=models.DateTimeField(
                blank=True, help_text="When promotion expires", null=True
            ),
        ),
    ]
