# Generated by Django 6.0.2 on 2026-02-20 17:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company_logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Company logo image (JPG, PNG, JPEG)",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
