# Generated by Django 6.0.2 on 2026-02-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_is_promoted_job_promoted_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_promoted",
        ),
        migrations.RemoveField(
            model_name="job",
            name="promoted_until",
        ),
    ]
