# Generated by Django 6.0.2 on 2026-02-23 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0002_job_is_promoted_job_promoted_until"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Package name (e.g., 'Basic', 'Premium')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Package description and benefits"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Package price in base currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=30,
                        help_text="How many days the promotion lasts",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "featured_position",
                    models.IntegerField(
                        default=3,
                        help_text="Display priority in job listings (lower = higher priority)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this package is available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Promotion Packages",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount in base currency",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="BDT",
                        help_text="Currency code (BDT for Bangladesh)",
                        max_length=3,
                    ),
                ),
                (
                    "store_id",
                    models.CharField(
                        blank=True, help_text="SSLCOMMERZ Store ID", max_length=50
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Unique transaction reference ID",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "validation_id",
                    models.CharField(
                        blank=True,
                        help_text="SSLCOMMERZ validation reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="initiated",
                        help_text="Current payment status",
                        max_length=20,
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full response from SSLCOMMERZ API",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if payment failed"
                    ),
                ),
                (
                    "is_job_promoted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether job post is promoted after payment",
                    ),
                ),
                (
                    "promotion_duration_days",
                    models.IntegerField(
                        default=30,
                        help_text="Days the job remains promoted",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "promoted_until",
                    models.DateTimeField(
                        blank=True, help_text="When the promotion expires", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Payment initiation time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last update time"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job post being promoted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_payments",
                        to="jobs.job",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        help_text="Recruiter making the payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_promotion_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initiated", "Payment Initiated"),
                            ("redirect_sent", "User Redirected to SSLCOMMERZ"),
                            ("callback_received", "Callback Received from SSLCOMMERZ"),
                            ("validation_started", "Validation Started"),
                            ("validation_success", "Validation Successful"),
                            ("validation_failed", "Validation Failed"),
                            ("job_promoted", "Job Promoted"),
                            ("error_occurred", "Error Occurred"),
                        ],
                        help_text="Action performed",
                        max_length=30,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional details about the action",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which action was initiated",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="Associated payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["recruiter", "-created_at"],
                name="payments_pa_recruit_ad3a19_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["job", "status"], name="payments_pa_job_id_dde10c_idx"
            ),
        ),
    ]
